### ISSUE TITLE
Unable to install chroma viz package windows 11

### ISSUE THREAD

**Issue by namantejaswi** [mtybadger/chromaviz#10]
Error when trying to install chroma viz package

ERROR: Could not find a version that satisfies the requirement chromaviz (from versions: none)
ERROR: No matching distribution found for chromaviz

Getting requirements to build wheel did not run successfully.

**Comment by SteveZZZZ** [comment]
Getting the Same Issue

**Comment by SRenuuu** [comment]
Getting the same issue on MacOS Sonoma (ARM64)

**Comment by stwater20** [comment]
same issue

**Comment by catalin-hanga** [comment]
same issue in Windows 10

**Comment by Vikram-HTC** [comment]
same here for mac

**Comment by txvmkkfknv** [comment]
same in google colab as well

**Comment by zmnv** [comment]
I had the error:

```
> pip install chromaviz
ERROR: Could not find a version that satisfies the requirement chromaviz (from versions: none)
ERROR: No matching distribution found for chromaviz
```

So...
check pull requests, it has a solution
https://github.com/mtybadger/chromaviz/pull/8

can be installed via:
```
pip install git+https://github.com/wyatt/chromaviz/
```

**Comment by namantejaswi** [comment]
> I had the error:
> 
> ```
> > pip install chromaviz
> ERROR: Could not find a version that satisfies the requirement chromaviz (from versions: none)
> ERROR: No matching distribution found for chromaviz
> ```
> 
> So... check pull requests, it has a solution #8
> 
> can be installed via:
> 
> ```
> pip install git+https://github.com/wyatt/chromaviz/
> ```

This works, thanks for sharing.

**Comment by coffeecodeconverter** [comment]
this may or may not help too - full instructions for installing on windows
https://github.com/mtybadger/chromaviz/issues/14

about midway, it covers the same step/fix mentioned in  https://github.com/mtybadger/chromaviz/pull/8
but also provides batch files to make it easier to launch the App in a virtual environment
