### ISSUE TITLE
Compatibility Issue with Latest Version of ChromaDB in ChromaViz Library

### ISSUE THREAD

**Issue by zinojeng** [mtybadger/chromaviz#4]
Dear mtybadger,

I am writing to bring to your attention an issue I encountered while using your ChromaViz library alongside the latest version of ChromaDB.

As you may be aware, ChromaDB has recently released an update that involves changes to its client construction and data persistence methods. After updating to this new version, I found that the visualize_collection function in ChromaViz is still using a deprecated configuration of ChromaDB, causing a ValueError to be thrown.

The error message suggests visiting the ChromaDB migration documentation (https://docs.trychroma.com/migration) to understand how to change the client construction. After following these guidelines, the issue still persists.

Here's a snippet of the code causing the issue:
`from chromaviz import visualize_collection
visualize_collection(chromadb.Collection)`

And the error message:
`ValueError: You are using a deprecated configuration of Chroma. ...`

I would greatly appreciate it if you could look into this matter and possibly release an update to make ChromaViz compatible with the latest version of ChromaDB.

Thank you for your time and consideration. I look forward to your response.

Best regards, Ander

**Comment by selamanse** [comment]
@zinojeng I think I know why this happens. The client was introduced by my change #1 and is not used anywhere. 

I removed it in #5 and also added a testfile chromaviz-test.py which can be used for further reference (and manual testing).

**Comment by selamanse** [comment]
while not merged you can test my change via

`pip install git+https://github.com/selamanse/chromaviz@fix_chromadb_error`
